fr.labedan.smartsheet_reader:
  src: /home/pol/work/plab/knime/basic/smartsheet_reader
  conda_env_path: /home/pol/work/plab/knime/basic/conda_env
  debug_mode: true
fr.labedan.smartsheet_writer:
  src: /home/pol/work/plab/knime/basic/smartsheet_writer
  conda_env_path: /home/pol/work/plab/knime/basic/conda_env
  debug_mode: true
